### 什么是重入攻击

> 计算机程序或子程序在执行过程中中断，然后在它前一次调用完成执行之前再次进行调用，那么该程序或子程序称为重入程序。中断可能是内部操作(如jump或call)或外部操作（如interrupt或signal）引起的。重入调用完成后，以前的调用将恢复正常执行。使用某些代码段执行此操作将导致重入攻击。
>
> 在以太坊智能合约中，合约能够调用和利用其他外部合约的代码。合约在正常执行期间可以通过执行函数调用或简单地转移以太币来执行对其他合约的调用。这些外部调用可以被攻击者劫持，从而强制合约执行下一步代码（即通过fallback函数），包括回调自身。在这种情况下，我们可以说合约被重入。



### 单函数重入

```solidity
mapping(address => uint) public balances;
function withdraw() external{
	uint256 _amount = balances[msg.sender];
	require(msg.sender.call{value:_mount}(""));//(1)
	balances[msg.sender] = 0; //(2)
}
```



### 跨函数重入

当一个易受攻击的函数与一个可被攻击者利用的**函数共享状态**时，就会发生跨函数重入。

```solidity
contract Vulnerable{
	...
	function getBonus Withdraw(){
		require(!Bonus[msg.sender]);
		Reward[] += 0.1 ether;
		withdrawAll[msg.sender];
		Bonus[msg.sender] = true;
	}
	function withdrawAll(){
		uint amount = Reward[msg.sender];
		Reward[msg.sender] = 0;
		require(msg.sender.call.value(amount)());
	}
}
```



```solidity
mapping(address => uint) public balance;

function transfer(address to , uint _amount) external{
	if(shares[msg.sender] >= _amount){
		shares[to] += _amount;
		shares[msg.sender] -= _amount;
	}
}

function withdraw() external{
	uint256 _amount = balances[msg.sender];
	require(msg.sender.call{value:_amount}(""));
	shares[msg.sender] = 0;
}
```

在此示例中，黑客可以利用fallback()操作该合约，外部调用transfer()函数，在合约余额状态设置为0之前，进行转移资金。虽然该合约能够接受到取款，但是也可以转移资金。

### 跨合约重入

当一个合约中的一个状态在另一个合约中使用，但在被调用之前未完全更新时，可能会发生跨合约重入。

跨合约重入所需以下条件：

(1)一个合约中的状态在另一个合约中共享或使用

(2)攻击者可以通过利用执行流来操纵合约的状态

